# Generated by Django 4.2.3 on 2023-07-05 17:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Place',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150, verbose_name='Название')),
                ('description_short', models.CharField(max_length=255, verbose_name='Краткое описание')),
                ('description_long', models.TextField(verbose_name='Развёрнутое описание')),
                ('сoordinates_lng', models.FloatField()),
                ('сoordinates_lat', models.FloatField()),
            ],
            options={
                'verbose_name': 'Место',
                'verbose_name_plural': 'Места',
            },
        ),
    ]
