# Generated by Django 4.2.3 on 2023-07-07 16:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('places', '0003_alter_image_place'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='image',
            options={'ordering': ['order'], 'verbose_name': 'Изображение', 'verbose_name_plural': 'Изображения'},
        ),
        migrations.AlterField(
            model_name='image',
            name='order',
            field=models.PositiveIntegerField(default=1, verbose_name='Порядковый номер'),
        ),
        migrations.AlterField(
            model_name='place',
            name='coordinates_lat',
            field=models.FloatField(verbose_name='Координаты: широта'),
        ),
        migrations.AlterField(
            model_name='place',
            name='coordinates_lng',
            field=models.FloatField(verbose_name='Координаты: долгота'),
        ),
    ]
